/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as ParentRouteImport } from './routes/_parent'
import { Route as FacilityRouteImport } from './routes/_facility'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacilitiesIndexRouteImport } from './routes/facilities/index'
import { Route as InviteCodeRouteImport } from './routes/invite/$code'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as FacilitiesFacilityIdIndexRouteImport } from './routes/facilities/$facilityId/index'
import { Route as StaffStaffIndexRouteImport } from './routes/_staff/staff/index'
import { Route as ParentParentIndexRouteImport } from './routes/_parent/parent/index'
import { Route as FacilityFacilityIndexRouteImport } from './routes/_facility/facility/index'
import { Route as FacilitiesFacilityIdReviewRouteImport } from './routes/facilities/$facilityId/review'
import { Route as FacilitiesFacilityIdEnrollRouteImport } from './routes/facilities/$facilityId/enroll'
import { Route as StaffStaffSettingsRouteImport } from './routes/_staff/staff/settings'
import { Route as StaffStaffNotificationsRouteImport } from './routes/_staff/staff/notifications'
import { Route as ParentParentSettingsRouteImport } from './routes/_parent/parent/settings'
import { Route as ParentParentReviewsRouteImport } from './routes/_parent/parent/reviews'
import { Route as ParentParentNotificationsRouteImport } from './routes/_parent/parent/notifications'
import { Route as FacilityFacilitySettingsRouteImport } from './routes/_facility/facility/settings'
import { Route as FacilityFacilityNotificationsRouteImport } from './routes/_facility/facility/notifications'
import { Route as FacilityFacilityNewRouteImport } from './routes/_facility/facility/new'
import { Route as StaffStaffMessagesIndexRouteImport } from './routes/_staff/staff/messages/index'
import { Route as ParentParentMessagesIndexRouteImport } from './routes/_parent/parent/messages/index'
import { Route as ParentParentDocumentsIndexRouteImport } from './routes/_parent/parent/documents/index'
import { Route as ParentParentChildrenIndexRouteImport } from './routes/_parent/parent/children/index'
import { Route as ParentParentBillingIndexRouteImport } from './routes/_parent/parent/billing/index'
import { Route as FacilityFacilityMessagesIndexRouteImport } from './routes/_facility/facility/messages/index'
import { Route as FacilityFacilityFacilityIdIndexRouteImport } from './routes/_facility/facility/$facilityId/index'
import { Route as StaffStaffMessagesConversationIdRouteImport } from './routes/_staff/staff/messages/$conversationId'
import { Route as ParentParentMessagesConversationIdRouteImport } from './routes/_parent/parent/messages/$conversationId'
import { Route as ParentParentEnrollmentsEnrollmentIdRouteImport } from './routes/_parent/parent/enrollments/$enrollmentId'
import { Route as ParentParentDocumentsDocumentIdRouteImport } from './routes/_parent/parent/documents/$documentId'
import { Route as ParentParentChildrenNewRouteImport } from './routes/_parent/parent/children/new'
import { Route as ParentParentChildrenChildIdRouteImport } from './routes/_parent/parent/children/$childId'
import { Route as ParentParentBillingPaymentsRouteImport } from './routes/_parent/parent/billing/payments'
import { Route as ParentParentBillingPaymentMethodsRouteImport } from './routes/_parent/parent/billing/payment-methods'
import { Route as FacilityFacilityMessagesConversationIdRouteImport } from './routes/_facility/facility/messages/$conversationId'
import { Route as FacilityFacilityFacilityIdStaffRouteImport } from './routes/_facility/facility/$facilityId/staff'
import { Route as FacilityFacilityFacilityIdServicesRouteImport } from './routes/_facility/facility/$facilityId/services'
import { Route as FacilityFacilityFacilityIdRosterRouteImport } from './routes/_facility/facility/$facilityId/roster'
import { Route as FacilityFacilityFacilityIdReviewsRouteImport } from './routes/_facility/facility/$facilityId/reviews'
import { Route as FacilityFacilityFacilityIdReportsRouteImport } from './routes/_facility/facility/$facilityId/reports'
import { Route as FacilityFacilityFacilityIdPhotosRouteImport } from './routes/_facility/facility/$facilityId/photos'
import { Route as FacilityFacilityFacilityIdInvitesRouteImport } from './routes/_facility/facility/$facilityId/invites'
import { Route as FacilityFacilityFacilityIdHoursRouteImport } from './routes/_facility/facility/$facilityId/hours'
import { Route as FacilityFacilityFacilityIdEnrollmentsRouteImport } from './routes/_facility/facility/$facilityId/enrollments'
import { Route as FacilityFacilityFacilityIdEditRouteImport } from './routes/_facility/facility/$facilityId/edit'
import { Route as FacilityFacilityFacilityIdDailyReportsRouteImport } from './routes/_facility/facility/$facilityId/daily-reports'
import { Route as FacilityFacilityFacilityIdAttendanceRouteImport } from './routes/_facility/facility/$facilityId/attendance'
import { Route as FacilityFacilityFacilityIdActivitiesRouteImport } from './routes/_facility/facility/$facilityId/activities'
import { Route as FacilityFacilityFacilityIdDocumentsIndexRouteImport } from './routes/_facility/facility/$facilityId/documents/index'
import { Route as FacilityFacilityFacilityIdBillingIndexRouteImport } from './routes/_facility/facility/$facilityId/billing/index'
import { Route as ParentParentChildrenChildIdPhotosRouteImport } from './routes/_parent/parent/children/$childId/photos'
import { Route as ParentParentChildrenChildIdEditRouteImport } from './routes/_parent/parent/children/$childId/edit'
import { Route as ParentParentChildrenChildIdActivitiesRouteImport } from './routes/_parent/parent/children/$childId/activities'
import { Route as ParentParentBillingInvoicesInvoiceIdRouteImport } from './routes/_parent/parent/billing/invoices/$invoiceId'
import { Route as FacilityFacilityFacilityIdInvitesFormsRouteImport } from './routes/_facility/facility/$facilityId/invites/forms'
import { Route as FacilityFacilityFacilityIdDocumentsTemplatesRouteImport } from './routes/_facility/facility/$facilityId/documents/templates'
import { Route as FacilityFacilityFacilityIdDocumentsSendRouteImport } from './routes/_facility/facility/$facilityId/documents/send'
import { Route as FacilityFacilityFacilityIdDocumentsComplianceRouteImport } from './routes/_facility/facility/$facilityId/documents/compliance'
import { Route as FacilityFacilityFacilityIdBillingInvoicesIndexRouteImport } from './routes/_facility/facility/$facilityId/billing/invoices/index'
import { Route as ParentParentChildrenChildIdDailyReportDateRouteImport } from './routes/_parent/parent/children/$childId/daily-report/$date'
import { Route as FacilityFacilityFacilityIdBillingInvoicesNewRouteImport } from './routes/_facility/facility/$facilityId/billing/invoices/new'
import { Route as FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRouteImport } from './routes/_facility/facility/$facilityId/billing/invoices/$invoiceId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/_parent',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/_facility',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesIndexRoute = FacilitiesIndexRouteImport.update({
  id: '/facilities/',
  path: '/facilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const FacilitiesFacilityIdIndexRoute =
  FacilitiesFacilityIdIndexRouteImport.update({
    id: '/facilities/$facilityId/',
    path: '/facilities/$facilityId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffStaffIndexRoute = StaffStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => StaffRoute,
} as any)
const ParentParentIndexRoute = ParentParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => ParentRoute,
} as any)
const FacilityFacilityIndexRoute = FacilityFacilityIndexRouteImport.update({
  id: '/facility/',
  path: '/facility/',
  getParentRoute: () => FacilityRoute,
} as any)
const FacilitiesFacilityIdReviewRoute =
  FacilitiesFacilityIdReviewRouteImport.update({
    id: '/facilities/$facilityId/review',
    path: '/facilities/$facilityId/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const FacilitiesFacilityIdEnrollRoute =
  FacilitiesFacilityIdEnrollRouteImport.update({
    id: '/facilities/$facilityId/enroll',
    path: '/facilities/$facilityId/enroll',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffStaffSettingsRoute = StaffStaffSettingsRouteImport.update({
  id: '/staff/settings',
  path: '/staff/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffNotificationsRoute = StaffStaffNotificationsRouteImport.update({
  id: '/staff/notifications',
  path: '/staff/notifications',
  getParentRoute: () => StaffRoute,
} as any)
const ParentParentSettingsRoute = ParentParentSettingsRouteImport.update({
  id: '/parent/settings',
  path: '/parent/settings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentParentReviewsRoute = ParentParentReviewsRouteImport.update({
  id: '/parent/reviews',
  path: '/parent/reviews',
  getParentRoute: () => ParentRoute,
} as any)
const ParentParentNotificationsRoute =
  ParentParentNotificationsRouteImport.update({
    id: '/parent/notifications',
    path: '/parent/notifications',
    getParentRoute: () => ParentRoute,
  } as any)
const FacilityFacilitySettingsRoute =
  FacilityFacilitySettingsRouteImport.update({
    id: '/facility/settings',
    path: '/facility/settings',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityNotificationsRoute =
  FacilityFacilityNotificationsRouteImport.update({
    id: '/facility/notifications',
    path: '/facility/notifications',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityNewRoute = FacilityFacilityNewRouteImport.update({
  id: '/facility/new',
  path: '/facility/new',
  getParentRoute: () => FacilityRoute,
} as any)
const StaffStaffMessagesIndexRoute = StaffStaffMessagesIndexRouteImport.update({
  id: '/staff/messages/',
  path: '/staff/messages/',
  getParentRoute: () => StaffRoute,
} as any)
const ParentParentMessagesIndexRoute =
  ParentParentMessagesIndexRouteImport.update({
    id: '/parent/messages/',
    path: '/parent/messages/',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentParentDocumentsIndexRoute =
  ParentParentDocumentsIndexRouteImport.update({
    id: '/parent/documents/',
    path: '/parent/documents/',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentParentChildrenIndexRoute =
  ParentParentChildrenIndexRouteImport.update({
    id: '/parent/children/',
    path: '/parent/children/',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentParentBillingIndexRoute =
  ParentParentBillingIndexRouteImport.update({
    id: '/parent/billing/',
    path: '/parent/billing/',
    getParentRoute: () => ParentRoute,
  } as any)
const FacilityFacilityMessagesIndexRoute =
  FacilityFacilityMessagesIndexRouteImport.update({
    id: '/facility/messages/',
    path: '/facility/messages/',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdIndexRoute =
  FacilityFacilityFacilityIdIndexRouteImport.update({
    id: '/facility/$facilityId/',
    path: '/facility/$facilityId/',
    getParentRoute: () => FacilityRoute,
  } as any)
const StaffStaffMessagesConversationIdRoute =
  StaffStaffMessagesConversationIdRouteImport.update({
    id: '/staff/messages/$conversationId',
    path: '/staff/messages/$conversationId',
    getParentRoute: () => StaffRoute,
  } as any)
const ParentParentMessagesConversationIdRoute =
  ParentParentMessagesConversationIdRouteImport.update({
    id: '/parent/messages/$conversationId',
    path: '/parent/messages/$conversationId',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentParentEnrollmentsEnrollmentIdRoute =
  ParentParentEnrollmentsEnrollmentIdRouteImport.update({
    id: '/parent/enrollments/$enrollmentId',
    path: '/parent/enrollments/$enrollmentId',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentParentDocumentsDocumentIdRoute =
  ParentParentDocumentsDocumentIdRouteImport.update({
    id: '/parent/documents/$documentId',
    path: '/parent/documents/$documentId',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentParentChildrenNewRoute = ParentParentChildrenNewRouteImport.update({
  id: '/parent/children/new',
  path: '/parent/children/new',
  getParentRoute: () => ParentRoute,
} as any)
const ParentParentChildrenChildIdRoute =
  ParentParentChildrenChildIdRouteImport.update({
    id: '/parent/children/$childId',
    path: '/parent/children/$childId',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentParentBillingPaymentsRoute =
  ParentParentBillingPaymentsRouteImport.update({
    id: '/parent/billing/payments',
    path: '/parent/billing/payments',
    getParentRoute: () => ParentRoute,
  } as any)
const ParentParentBillingPaymentMethodsRoute =
  ParentParentBillingPaymentMethodsRouteImport.update({
    id: '/parent/billing/payment-methods',
    path: '/parent/billing/payment-methods',
    getParentRoute: () => ParentRoute,
  } as any)
const FacilityFacilityMessagesConversationIdRoute =
  FacilityFacilityMessagesConversationIdRouteImport.update({
    id: '/facility/messages/$conversationId',
    path: '/facility/messages/$conversationId',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdStaffRoute =
  FacilityFacilityFacilityIdStaffRouteImport.update({
    id: '/facility/$facilityId/staff',
    path: '/facility/$facilityId/staff',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdServicesRoute =
  FacilityFacilityFacilityIdServicesRouteImport.update({
    id: '/facility/$facilityId/services',
    path: '/facility/$facilityId/services',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdRosterRoute =
  FacilityFacilityFacilityIdRosterRouteImport.update({
    id: '/facility/$facilityId/roster',
    path: '/facility/$facilityId/roster',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdReviewsRoute =
  FacilityFacilityFacilityIdReviewsRouteImport.update({
    id: '/facility/$facilityId/reviews',
    path: '/facility/$facilityId/reviews',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdReportsRoute =
  FacilityFacilityFacilityIdReportsRouteImport.update({
    id: '/facility/$facilityId/reports',
    path: '/facility/$facilityId/reports',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdPhotosRoute =
  FacilityFacilityFacilityIdPhotosRouteImport.update({
    id: '/facility/$facilityId/photos',
    path: '/facility/$facilityId/photos',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdInvitesRoute =
  FacilityFacilityFacilityIdInvitesRouteImport.update({
    id: '/facility/$facilityId/invites',
    path: '/facility/$facilityId/invites',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdHoursRoute =
  FacilityFacilityFacilityIdHoursRouteImport.update({
    id: '/facility/$facilityId/hours',
    path: '/facility/$facilityId/hours',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdEnrollmentsRoute =
  FacilityFacilityFacilityIdEnrollmentsRouteImport.update({
    id: '/facility/$facilityId/enrollments',
    path: '/facility/$facilityId/enrollments',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdEditRoute =
  FacilityFacilityFacilityIdEditRouteImport.update({
    id: '/facility/$facilityId/edit',
    path: '/facility/$facilityId/edit',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdDailyReportsRoute =
  FacilityFacilityFacilityIdDailyReportsRouteImport.update({
    id: '/facility/$facilityId/daily-reports',
    path: '/facility/$facilityId/daily-reports',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdAttendanceRoute =
  FacilityFacilityFacilityIdAttendanceRouteImport.update({
    id: '/facility/$facilityId/attendance',
    path: '/facility/$facilityId/attendance',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdActivitiesRoute =
  FacilityFacilityFacilityIdActivitiesRouteImport.update({
    id: '/facility/$facilityId/activities',
    path: '/facility/$facilityId/activities',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdDocumentsIndexRoute =
  FacilityFacilityFacilityIdDocumentsIndexRouteImport.update({
    id: '/facility/$facilityId/documents/',
    path: '/facility/$facilityId/documents/',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdBillingIndexRoute =
  FacilityFacilityFacilityIdBillingIndexRouteImport.update({
    id: '/facility/$facilityId/billing/',
    path: '/facility/$facilityId/billing/',
    getParentRoute: () => FacilityRoute,
  } as any)
const ParentParentChildrenChildIdPhotosRoute =
  ParentParentChildrenChildIdPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => ParentParentChildrenChildIdRoute,
  } as any)
const ParentParentChildrenChildIdEditRoute =
  ParentParentChildrenChildIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ParentParentChildrenChildIdRoute,
  } as any)
const ParentParentChildrenChildIdActivitiesRoute =
  ParentParentChildrenChildIdActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => ParentParentChildrenChildIdRoute,
  } as any)
const ParentParentBillingInvoicesInvoiceIdRoute =
  ParentParentBillingInvoicesInvoiceIdRouteImport.update({
    id: '/parent/billing/invoices/$invoiceId',
    path: '/parent/billing/invoices/$invoiceId',
    getParentRoute: () => ParentRoute,
  } as any)
const FacilityFacilityFacilityIdInvitesFormsRoute =
  FacilityFacilityFacilityIdInvitesFormsRouteImport.update({
    id: '/forms',
    path: '/forms',
    getParentRoute: () => FacilityFacilityFacilityIdInvitesRoute,
  } as any)
const FacilityFacilityFacilityIdDocumentsTemplatesRoute =
  FacilityFacilityFacilityIdDocumentsTemplatesRouteImport.update({
    id: '/facility/$facilityId/documents/templates',
    path: '/facility/$facilityId/documents/templates',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdDocumentsSendRoute =
  FacilityFacilityFacilityIdDocumentsSendRouteImport.update({
    id: '/facility/$facilityId/documents/send',
    path: '/facility/$facilityId/documents/send',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdDocumentsComplianceRoute =
  FacilityFacilityFacilityIdDocumentsComplianceRouteImport.update({
    id: '/facility/$facilityId/documents/compliance',
    path: '/facility/$facilityId/documents/compliance',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdBillingInvoicesIndexRoute =
  FacilityFacilityFacilityIdBillingInvoicesIndexRouteImport.update({
    id: '/facility/$facilityId/billing/invoices/',
    path: '/facility/$facilityId/billing/invoices/',
    getParentRoute: () => FacilityRoute,
  } as any)
const ParentParentChildrenChildIdDailyReportDateRoute =
  ParentParentChildrenChildIdDailyReportDateRouteImport.update({
    id: '/daily-report/$date',
    path: '/daily-report/$date',
    getParentRoute: () => ParentParentChildrenChildIdRoute,
  } as any)
const FacilityFacilityFacilityIdBillingInvoicesNewRoute =
  FacilityFacilityFacilityIdBillingInvoicesNewRouteImport.update({
    id: '/facility/$facilityId/billing/invoices/new',
    path: '/facility/$facilityId/billing/invoices/new',
    getParentRoute: () => FacilityRoute,
  } as any)
const FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRoute =
  FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRouteImport.update({
    id: '/facility/$facilityId/billing/invoices/$invoiceId',
    path: '/facility/$facilityId/billing/invoices/$invoiceId',
    getParentRoute: () => FacilityRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/$code': typeof InviteCodeRoute
  '/facilities/': typeof FacilitiesIndexRoute
  '/facility/new': typeof FacilityFacilityNewRoute
  '/facility/notifications': typeof FacilityFacilityNotificationsRoute
  '/facility/settings': typeof FacilityFacilitySettingsRoute
  '/parent/notifications': typeof ParentParentNotificationsRoute
  '/parent/reviews': typeof ParentParentReviewsRoute
  '/parent/settings': typeof ParentParentSettingsRoute
  '/staff/notifications': typeof StaffStaffNotificationsRoute
  '/staff/settings': typeof StaffStaffSettingsRoute
  '/facilities/$facilityId/enroll': typeof FacilitiesFacilityIdEnrollRoute
  '/facilities/$facilityId/review': typeof FacilitiesFacilityIdReviewRoute
  '/facility/': typeof FacilityFacilityIndexRoute
  '/parent/': typeof ParentParentIndexRoute
  '/staff/': typeof StaffStaffIndexRoute
  '/facilities/$facilityId/': typeof FacilitiesFacilityIdIndexRoute
  '/facility/$facilityId/activities': typeof FacilityFacilityFacilityIdActivitiesRoute
  '/facility/$facilityId/attendance': typeof FacilityFacilityFacilityIdAttendanceRoute
  '/facility/$facilityId/daily-reports': typeof FacilityFacilityFacilityIdDailyReportsRoute
  '/facility/$facilityId/edit': typeof FacilityFacilityFacilityIdEditRoute
  '/facility/$facilityId/enrollments': typeof FacilityFacilityFacilityIdEnrollmentsRoute
  '/facility/$facilityId/hours': typeof FacilityFacilityFacilityIdHoursRoute
  '/facility/$facilityId/invites': typeof FacilityFacilityFacilityIdInvitesRouteWithChildren
  '/facility/$facilityId/photos': typeof FacilityFacilityFacilityIdPhotosRoute
  '/facility/$facilityId/reports': typeof FacilityFacilityFacilityIdReportsRoute
  '/facility/$facilityId/reviews': typeof FacilityFacilityFacilityIdReviewsRoute
  '/facility/$facilityId/roster': typeof FacilityFacilityFacilityIdRosterRoute
  '/facility/$facilityId/services': typeof FacilityFacilityFacilityIdServicesRoute
  '/facility/$facilityId/staff': typeof FacilityFacilityFacilityIdStaffRoute
  '/facility/messages/$conversationId': typeof FacilityFacilityMessagesConversationIdRoute
  '/parent/billing/payment-methods': typeof ParentParentBillingPaymentMethodsRoute
  '/parent/billing/payments': typeof ParentParentBillingPaymentsRoute
  '/parent/children/$childId': typeof ParentParentChildrenChildIdRouteWithChildren
  '/parent/children/new': typeof ParentParentChildrenNewRoute
  '/parent/documents/$documentId': typeof ParentParentDocumentsDocumentIdRoute
  '/parent/enrollments/$enrollmentId': typeof ParentParentEnrollmentsEnrollmentIdRoute
  '/parent/messages/$conversationId': typeof ParentParentMessagesConversationIdRoute
  '/staff/messages/$conversationId': typeof StaffStaffMessagesConversationIdRoute
  '/facility/$facilityId/': typeof FacilityFacilityFacilityIdIndexRoute
  '/facility/messages/': typeof FacilityFacilityMessagesIndexRoute
  '/parent/billing/': typeof ParentParentBillingIndexRoute
  '/parent/children/': typeof ParentParentChildrenIndexRoute
  '/parent/documents/': typeof ParentParentDocumentsIndexRoute
  '/parent/messages/': typeof ParentParentMessagesIndexRoute
  '/staff/messages/': typeof StaffStaffMessagesIndexRoute
  '/facility/$facilityId/documents/compliance': typeof FacilityFacilityFacilityIdDocumentsComplianceRoute
  '/facility/$facilityId/documents/send': typeof FacilityFacilityFacilityIdDocumentsSendRoute
  '/facility/$facilityId/documents/templates': typeof FacilityFacilityFacilityIdDocumentsTemplatesRoute
  '/facility/$facilityId/invites/forms': typeof FacilityFacilityFacilityIdInvitesFormsRoute
  '/parent/billing/invoices/$invoiceId': typeof ParentParentBillingInvoicesInvoiceIdRoute
  '/parent/children/$childId/activities': typeof ParentParentChildrenChildIdActivitiesRoute
  '/parent/children/$childId/edit': typeof ParentParentChildrenChildIdEditRoute
  '/parent/children/$childId/photos': typeof ParentParentChildrenChildIdPhotosRoute
  '/facility/$facilityId/billing/': typeof FacilityFacilityFacilityIdBillingIndexRoute
  '/facility/$facilityId/documents/': typeof FacilityFacilityFacilityIdDocumentsIndexRoute
  '/facility/$facilityId/billing/invoices/$invoiceId': typeof FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRoute
  '/facility/$facilityId/billing/invoices/new': typeof FacilityFacilityFacilityIdBillingInvoicesNewRoute
  '/parent/children/$childId/daily-report/$date': typeof ParentParentChildrenChildIdDailyReportDateRoute
  '/facility/$facilityId/billing/invoices/': typeof FacilityFacilityFacilityIdBillingInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/invite/$code': typeof InviteCodeRoute
  '/facilities': typeof FacilitiesIndexRoute
  '/facility/new': typeof FacilityFacilityNewRoute
  '/facility/notifications': typeof FacilityFacilityNotificationsRoute
  '/facility/settings': typeof FacilityFacilitySettingsRoute
  '/parent/notifications': typeof ParentParentNotificationsRoute
  '/parent/reviews': typeof ParentParentReviewsRoute
  '/parent/settings': typeof ParentParentSettingsRoute
  '/staff/notifications': typeof StaffStaffNotificationsRoute
  '/staff/settings': typeof StaffStaffSettingsRoute
  '/facilities/$facilityId/enroll': typeof FacilitiesFacilityIdEnrollRoute
  '/facilities/$facilityId/review': typeof FacilitiesFacilityIdReviewRoute
  '/facility': typeof FacilityFacilityIndexRoute
  '/parent': typeof ParentParentIndexRoute
  '/staff': typeof StaffStaffIndexRoute
  '/facilities/$facilityId': typeof FacilitiesFacilityIdIndexRoute
  '/facility/$facilityId/activities': typeof FacilityFacilityFacilityIdActivitiesRoute
  '/facility/$facilityId/attendance': typeof FacilityFacilityFacilityIdAttendanceRoute
  '/facility/$facilityId/daily-reports': typeof FacilityFacilityFacilityIdDailyReportsRoute
  '/facility/$facilityId/edit': typeof FacilityFacilityFacilityIdEditRoute
  '/facility/$facilityId/enrollments': typeof FacilityFacilityFacilityIdEnrollmentsRoute
  '/facility/$facilityId/hours': typeof FacilityFacilityFacilityIdHoursRoute
  '/facility/$facilityId/invites': typeof FacilityFacilityFacilityIdInvitesRouteWithChildren
  '/facility/$facilityId/photos': typeof FacilityFacilityFacilityIdPhotosRoute
  '/facility/$facilityId/reports': typeof FacilityFacilityFacilityIdReportsRoute
  '/facility/$facilityId/reviews': typeof FacilityFacilityFacilityIdReviewsRoute
  '/facility/$facilityId/roster': typeof FacilityFacilityFacilityIdRosterRoute
  '/facility/$facilityId/services': typeof FacilityFacilityFacilityIdServicesRoute
  '/facility/$facilityId/staff': typeof FacilityFacilityFacilityIdStaffRoute
  '/facility/messages/$conversationId': typeof FacilityFacilityMessagesConversationIdRoute
  '/parent/billing/payment-methods': typeof ParentParentBillingPaymentMethodsRoute
  '/parent/billing/payments': typeof ParentParentBillingPaymentsRoute
  '/parent/children/$childId': typeof ParentParentChildrenChildIdRouteWithChildren
  '/parent/children/new': typeof ParentParentChildrenNewRoute
  '/parent/documents/$documentId': typeof ParentParentDocumentsDocumentIdRoute
  '/parent/enrollments/$enrollmentId': typeof ParentParentEnrollmentsEnrollmentIdRoute
  '/parent/messages/$conversationId': typeof ParentParentMessagesConversationIdRoute
  '/staff/messages/$conversationId': typeof StaffStaffMessagesConversationIdRoute
  '/facility/$facilityId': typeof FacilityFacilityFacilityIdIndexRoute
  '/facility/messages': typeof FacilityFacilityMessagesIndexRoute
  '/parent/billing': typeof ParentParentBillingIndexRoute
  '/parent/children': typeof ParentParentChildrenIndexRoute
  '/parent/documents': typeof ParentParentDocumentsIndexRoute
  '/parent/messages': typeof ParentParentMessagesIndexRoute
  '/staff/messages': typeof StaffStaffMessagesIndexRoute
  '/facility/$facilityId/documents/compliance': typeof FacilityFacilityFacilityIdDocumentsComplianceRoute
  '/facility/$facilityId/documents/send': typeof FacilityFacilityFacilityIdDocumentsSendRoute
  '/facility/$facilityId/documents/templates': typeof FacilityFacilityFacilityIdDocumentsTemplatesRoute
  '/facility/$facilityId/invites/forms': typeof FacilityFacilityFacilityIdInvitesFormsRoute
  '/parent/billing/invoices/$invoiceId': typeof ParentParentBillingInvoicesInvoiceIdRoute
  '/parent/children/$childId/activities': typeof ParentParentChildrenChildIdActivitiesRoute
  '/parent/children/$childId/edit': typeof ParentParentChildrenChildIdEditRoute
  '/parent/children/$childId/photos': typeof ParentParentChildrenChildIdPhotosRoute
  '/facility/$facilityId/billing': typeof FacilityFacilityFacilityIdBillingIndexRoute
  '/facility/$facilityId/documents': typeof FacilityFacilityFacilityIdDocumentsIndexRoute
  '/facility/$facilityId/billing/invoices/$invoiceId': typeof FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRoute
  '/facility/$facilityId/billing/invoices/new': typeof FacilityFacilityFacilityIdBillingInvoicesNewRoute
  '/parent/children/$childId/daily-report/$date': typeof ParentParentChildrenChildIdDailyReportDateRoute
  '/facility/$facilityId/billing/invoices': typeof FacilityFacilityFacilityIdBillingInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_facility': typeof FacilityRouteWithChildren
  '/_parent': typeof ParentRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/invite/$code': typeof InviteCodeRoute
  '/facilities/': typeof FacilitiesIndexRoute
  '/_facility/facility/new': typeof FacilityFacilityNewRoute
  '/_facility/facility/notifications': typeof FacilityFacilityNotificationsRoute
  '/_facility/facility/settings': typeof FacilityFacilitySettingsRoute
  '/_parent/parent/notifications': typeof ParentParentNotificationsRoute
  '/_parent/parent/reviews': typeof ParentParentReviewsRoute
  '/_parent/parent/settings': typeof ParentParentSettingsRoute
  '/_staff/staff/notifications': typeof StaffStaffNotificationsRoute
  '/_staff/staff/settings': typeof StaffStaffSettingsRoute
  '/facilities/$facilityId/enroll': typeof FacilitiesFacilityIdEnrollRoute
  '/facilities/$facilityId/review': typeof FacilitiesFacilityIdReviewRoute
  '/_facility/facility/': typeof FacilityFacilityIndexRoute
  '/_parent/parent/': typeof ParentParentIndexRoute
  '/_staff/staff/': typeof StaffStaffIndexRoute
  '/facilities/$facilityId/': typeof FacilitiesFacilityIdIndexRoute
  '/_facility/facility/$facilityId/activities': typeof FacilityFacilityFacilityIdActivitiesRoute
  '/_facility/facility/$facilityId/attendance': typeof FacilityFacilityFacilityIdAttendanceRoute
  '/_facility/facility/$facilityId/daily-reports': typeof FacilityFacilityFacilityIdDailyReportsRoute
  '/_facility/facility/$facilityId/edit': typeof FacilityFacilityFacilityIdEditRoute
  '/_facility/facility/$facilityId/enrollments': typeof FacilityFacilityFacilityIdEnrollmentsRoute
  '/_facility/facility/$facilityId/hours': typeof FacilityFacilityFacilityIdHoursRoute
  '/_facility/facility/$facilityId/invites': typeof FacilityFacilityFacilityIdInvitesRouteWithChildren
  '/_facility/facility/$facilityId/photos': typeof FacilityFacilityFacilityIdPhotosRoute
  '/_facility/facility/$facilityId/reports': typeof FacilityFacilityFacilityIdReportsRoute
  '/_facility/facility/$facilityId/reviews': typeof FacilityFacilityFacilityIdReviewsRoute
  '/_facility/facility/$facilityId/roster': typeof FacilityFacilityFacilityIdRosterRoute
  '/_facility/facility/$facilityId/services': typeof FacilityFacilityFacilityIdServicesRoute
  '/_facility/facility/$facilityId/staff': typeof FacilityFacilityFacilityIdStaffRoute
  '/_facility/facility/messages/$conversationId': typeof FacilityFacilityMessagesConversationIdRoute
  '/_parent/parent/billing/payment-methods': typeof ParentParentBillingPaymentMethodsRoute
  '/_parent/parent/billing/payments': typeof ParentParentBillingPaymentsRoute
  '/_parent/parent/children/$childId': typeof ParentParentChildrenChildIdRouteWithChildren
  '/_parent/parent/children/new': typeof ParentParentChildrenNewRoute
  '/_parent/parent/documents/$documentId': typeof ParentParentDocumentsDocumentIdRoute
  '/_parent/parent/enrollments/$enrollmentId': typeof ParentParentEnrollmentsEnrollmentIdRoute
  '/_parent/parent/messages/$conversationId': typeof ParentParentMessagesConversationIdRoute
  '/_staff/staff/messages/$conversationId': typeof StaffStaffMessagesConversationIdRoute
  '/_facility/facility/$facilityId/': typeof FacilityFacilityFacilityIdIndexRoute
  '/_facility/facility/messages/': typeof FacilityFacilityMessagesIndexRoute
  '/_parent/parent/billing/': typeof ParentParentBillingIndexRoute
  '/_parent/parent/children/': typeof ParentParentChildrenIndexRoute
  '/_parent/parent/documents/': typeof ParentParentDocumentsIndexRoute
  '/_parent/parent/messages/': typeof ParentParentMessagesIndexRoute
  '/_staff/staff/messages/': typeof StaffStaffMessagesIndexRoute
  '/_facility/facility/$facilityId/documents/compliance': typeof FacilityFacilityFacilityIdDocumentsComplianceRoute
  '/_facility/facility/$facilityId/documents/send': typeof FacilityFacilityFacilityIdDocumentsSendRoute
  '/_facility/facility/$facilityId/documents/templates': typeof FacilityFacilityFacilityIdDocumentsTemplatesRoute
  '/_facility/facility/$facilityId/invites/forms': typeof FacilityFacilityFacilityIdInvitesFormsRoute
  '/_parent/parent/billing/invoices/$invoiceId': typeof ParentParentBillingInvoicesInvoiceIdRoute
  '/_parent/parent/children/$childId/activities': typeof ParentParentChildrenChildIdActivitiesRoute
  '/_parent/parent/children/$childId/edit': typeof ParentParentChildrenChildIdEditRoute
  '/_parent/parent/children/$childId/photos': typeof ParentParentChildrenChildIdPhotosRoute
  '/_facility/facility/$facilityId/billing/': typeof FacilityFacilityFacilityIdBillingIndexRoute
  '/_facility/facility/$facilityId/documents/': typeof FacilityFacilityFacilityIdDocumentsIndexRoute
  '/_facility/facility/$facilityId/billing/invoices/$invoiceId': typeof FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRoute
  '/_facility/facility/$facilityId/billing/invoices/new': typeof FacilityFacilityFacilityIdBillingInvoicesNewRoute
  '/_parent/parent/children/$childId/daily-report/$date': typeof ParentParentChildrenChildIdDailyReportDateRoute
  '/_facility/facility/$facilityId/billing/invoices/': typeof FacilityFacilityFacilityIdBillingInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/invite/$code'
    | '/facilities/'
    | '/facility/new'
    | '/facility/notifications'
    | '/facility/settings'
    | '/parent/notifications'
    | '/parent/reviews'
    | '/parent/settings'
    | '/staff/notifications'
    | '/staff/settings'
    | '/facilities/$facilityId/enroll'
    | '/facilities/$facilityId/review'
    | '/facility/'
    | '/parent/'
    | '/staff/'
    | '/facilities/$facilityId/'
    | '/facility/$facilityId/activities'
    | '/facility/$facilityId/attendance'
    | '/facility/$facilityId/daily-reports'
    | '/facility/$facilityId/edit'
    | '/facility/$facilityId/enrollments'
    | '/facility/$facilityId/hours'
    | '/facility/$facilityId/invites'
    | '/facility/$facilityId/photos'
    | '/facility/$facilityId/reports'
    | '/facility/$facilityId/reviews'
    | '/facility/$facilityId/roster'
    | '/facility/$facilityId/services'
    | '/facility/$facilityId/staff'
    | '/facility/messages/$conversationId'
    | '/parent/billing/payment-methods'
    | '/parent/billing/payments'
    | '/parent/children/$childId'
    | '/parent/children/new'
    | '/parent/documents/$documentId'
    | '/parent/enrollments/$enrollmentId'
    | '/parent/messages/$conversationId'
    | '/staff/messages/$conversationId'
    | '/facility/$facilityId/'
    | '/facility/messages/'
    | '/parent/billing/'
    | '/parent/children/'
    | '/parent/documents/'
    | '/parent/messages/'
    | '/staff/messages/'
    | '/facility/$facilityId/documents/compliance'
    | '/facility/$facilityId/documents/send'
    | '/facility/$facilityId/documents/templates'
    | '/facility/$facilityId/invites/forms'
    | '/parent/billing/invoices/$invoiceId'
    | '/parent/children/$childId/activities'
    | '/parent/children/$childId/edit'
    | '/parent/children/$childId/photos'
    | '/facility/$facilityId/billing/'
    | '/facility/$facilityId/documents/'
    | '/facility/$facilityId/billing/invoices/$invoiceId'
    | '/facility/$facilityId/billing/invoices/new'
    | '/parent/children/$childId/daily-report/$date'
    | '/facility/$facilityId/billing/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/unauthorized'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/invite/$code'
    | '/facilities'
    | '/facility/new'
    | '/facility/notifications'
    | '/facility/settings'
    | '/parent/notifications'
    | '/parent/reviews'
    | '/parent/settings'
    | '/staff/notifications'
    | '/staff/settings'
    | '/facilities/$facilityId/enroll'
    | '/facilities/$facilityId/review'
    | '/facility'
    | '/parent'
    | '/staff'
    | '/facilities/$facilityId'
    | '/facility/$facilityId/activities'
    | '/facility/$facilityId/attendance'
    | '/facility/$facilityId/daily-reports'
    | '/facility/$facilityId/edit'
    | '/facility/$facilityId/enrollments'
    | '/facility/$facilityId/hours'
    | '/facility/$facilityId/invites'
    | '/facility/$facilityId/photos'
    | '/facility/$facilityId/reports'
    | '/facility/$facilityId/reviews'
    | '/facility/$facilityId/roster'
    | '/facility/$facilityId/services'
    | '/facility/$facilityId/staff'
    | '/facility/messages/$conversationId'
    | '/parent/billing/payment-methods'
    | '/parent/billing/payments'
    | '/parent/children/$childId'
    | '/parent/children/new'
    | '/parent/documents/$documentId'
    | '/parent/enrollments/$enrollmentId'
    | '/parent/messages/$conversationId'
    | '/staff/messages/$conversationId'
    | '/facility/$facilityId'
    | '/facility/messages'
    | '/parent/billing'
    | '/parent/children'
    | '/parent/documents'
    | '/parent/messages'
    | '/staff/messages'
    | '/facility/$facilityId/documents/compliance'
    | '/facility/$facilityId/documents/send'
    | '/facility/$facilityId/documents/templates'
    | '/facility/$facilityId/invites/forms'
    | '/parent/billing/invoices/$invoiceId'
    | '/parent/children/$childId/activities'
    | '/parent/children/$childId/edit'
    | '/parent/children/$childId/photos'
    | '/facility/$facilityId/billing'
    | '/facility/$facilityId/documents'
    | '/facility/$facilityId/billing/invoices/$invoiceId'
    | '/facility/$facilityId/billing/invoices/new'
    | '/parent/children/$childId/daily-report/$date'
    | '/facility/$facilityId/billing/invoices'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_facility'
    | '/_parent'
    | '/_staff'
    | '/discover'
    | '/unauthorized'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/invite/$code'
    | '/facilities/'
    | '/_facility/facility/new'
    | '/_facility/facility/notifications'
    | '/_facility/facility/settings'
    | '/_parent/parent/notifications'
    | '/_parent/parent/reviews'
    | '/_parent/parent/settings'
    | '/_staff/staff/notifications'
    | '/_staff/staff/settings'
    | '/facilities/$facilityId/enroll'
    | '/facilities/$facilityId/review'
    | '/_facility/facility/'
    | '/_parent/parent/'
    | '/_staff/staff/'
    | '/facilities/$facilityId/'
    | '/_facility/facility/$facilityId/activities'
    | '/_facility/facility/$facilityId/attendance'
    | '/_facility/facility/$facilityId/daily-reports'
    | '/_facility/facility/$facilityId/edit'
    | '/_facility/facility/$facilityId/enrollments'
    | '/_facility/facility/$facilityId/hours'
    | '/_facility/facility/$facilityId/invites'
    | '/_facility/facility/$facilityId/photos'
    | '/_facility/facility/$facilityId/reports'
    | '/_facility/facility/$facilityId/reviews'
    | '/_facility/facility/$facilityId/roster'
    | '/_facility/facility/$facilityId/services'
    | '/_facility/facility/$facilityId/staff'
    | '/_facility/facility/messages/$conversationId'
    | '/_parent/parent/billing/payment-methods'
    | '/_parent/parent/billing/payments'
    | '/_parent/parent/children/$childId'
    | '/_parent/parent/children/new'
    | '/_parent/parent/documents/$documentId'
    | '/_parent/parent/enrollments/$enrollmentId'
    | '/_parent/parent/messages/$conversationId'
    | '/_staff/staff/messages/$conversationId'
    | '/_facility/facility/$facilityId/'
    | '/_facility/facility/messages/'
    | '/_parent/parent/billing/'
    | '/_parent/parent/children/'
    | '/_parent/parent/documents/'
    | '/_parent/parent/messages/'
    | '/_staff/staff/messages/'
    | '/_facility/facility/$facilityId/documents/compliance'
    | '/_facility/facility/$facilityId/documents/send'
    | '/_facility/facility/$facilityId/documents/templates'
    | '/_facility/facility/$facilityId/invites/forms'
    | '/_parent/parent/billing/invoices/$invoiceId'
    | '/_parent/parent/children/$childId/activities'
    | '/_parent/parent/children/$childId/edit'
    | '/_parent/parent/children/$childId/photos'
    | '/_facility/facility/$facilityId/billing/'
    | '/_facility/facility/$facilityId/documents/'
    | '/_facility/facility/$facilityId/billing/invoices/$invoiceId'
    | '/_facility/facility/$facilityId/billing/invoices/new'
    | '/_parent/parent/children/$childId/daily-report/$date'
    | '/_facility/facility/$facilityId/billing/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  FacilityRoute: typeof FacilityRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  InviteCodeRoute: typeof InviteCodeRoute
  FacilitiesIndexRoute: typeof FacilitiesIndexRoute
  FacilitiesFacilityIdEnrollRoute: typeof FacilitiesFacilityIdEnrollRoute
  FacilitiesFacilityIdReviewRoute: typeof FacilitiesFacilityIdReviewRoute
  FacilitiesFacilityIdIndexRoute: typeof FacilitiesFacilityIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_parent': {
      id: '/_parent'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_facility': {
      id: '/_facility'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities/': {
      id: '/facilities/'
      path: '/facilities'
      fullPath: '/facilities/'
      preLoaderRoute: typeof FacilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/facilities/$facilityId/': {
      id: '/facilities/$facilityId/'
      path: '/facilities/$facilityId'
      fullPath: '/facilities/$facilityId/'
      preLoaderRoute: typeof FacilitiesFacilityIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/staff/': {
      id: '/_staff/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffStaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_parent/parent/': {
      id: '/_parent/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_facility/facility/': {
      id: '/_facility/facility/'
      path: '/facility'
      fullPath: '/facility/'
      preLoaderRoute: typeof FacilityFacilityIndexRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/facilities/$facilityId/review': {
      id: '/facilities/$facilityId/review'
      path: '/facilities/$facilityId/review'
      fullPath: '/facilities/$facilityId/review'
      preLoaderRoute: typeof FacilitiesFacilityIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities/$facilityId/enroll': {
      id: '/facilities/$facilityId/enroll'
      path: '/facilities/$facilityId/enroll'
      fullPath: '/facilities/$facilityId/enroll'
      preLoaderRoute: typeof FacilitiesFacilityIdEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/staff/settings': {
      id: '/_staff/staff/settings'
      path: '/staff/settings'
      fullPath: '/staff/settings'
      preLoaderRoute: typeof StaffStaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/staff/notifications': {
      id: '/_staff/staff/notifications'
      path: '/staff/notifications'
      fullPath: '/staff/notifications'
      preLoaderRoute: typeof StaffStaffNotificationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_parent/parent/settings': {
      id: '/_parent/parent/settings'
      path: '/parent/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/reviews': {
      id: '/_parent/parent/reviews'
      path: '/parent/reviews'
      fullPath: '/parent/reviews'
      preLoaderRoute: typeof ParentParentReviewsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/notifications': {
      id: '/_parent/parent/notifications'
      path: '/parent/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof ParentParentNotificationsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_facility/facility/settings': {
      id: '/_facility/facility/settings'
      path: '/facility/settings'
      fullPath: '/facility/settings'
      preLoaderRoute: typeof FacilityFacilitySettingsRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/notifications': {
      id: '/_facility/facility/notifications'
      path: '/facility/notifications'
      fullPath: '/facility/notifications'
      preLoaderRoute: typeof FacilityFacilityNotificationsRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/new': {
      id: '/_facility/facility/new'
      path: '/facility/new'
      fullPath: '/facility/new'
      preLoaderRoute: typeof FacilityFacilityNewRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_staff/staff/messages/': {
      id: '/_staff/staff/messages/'
      path: '/staff/messages'
      fullPath: '/staff/messages/'
      preLoaderRoute: typeof StaffStaffMessagesIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_parent/parent/messages/': {
      id: '/_parent/parent/messages/'
      path: '/parent/messages'
      fullPath: '/parent/messages/'
      preLoaderRoute: typeof ParentParentMessagesIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/documents/': {
      id: '/_parent/parent/documents/'
      path: '/parent/documents'
      fullPath: '/parent/documents/'
      preLoaderRoute: typeof ParentParentDocumentsIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/children/': {
      id: '/_parent/parent/children/'
      path: '/parent/children'
      fullPath: '/parent/children/'
      preLoaderRoute: typeof ParentParentChildrenIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/billing/': {
      id: '/_parent/parent/billing/'
      path: '/parent/billing'
      fullPath: '/parent/billing/'
      preLoaderRoute: typeof ParentParentBillingIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_facility/facility/messages/': {
      id: '/_facility/facility/messages/'
      path: '/facility/messages'
      fullPath: '/facility/messages/'
      preLoaderRoute: typeof FacilityFacilityMessagesIndexRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/': {
      id: '/_facility/facility/$facilityId/'
      path: '/facility/$facilityId'
      fullPath: '/facility/$facilityId/'
      preLoaderRoute: typeof FacilityFacilityFacilityIdIndexRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_staff/staff/messages/$conversationId': {
      id: '/_staff/staff/messages/$conversationId'
      path: '/staff/messages/$conversationId'
      fullPath: '/staff/messages/$conversationId'
      preLoaderRoute: typeof StaffStaffMessagesConversationIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_parent/parent/messages/$conversationId': {
      id: '/_parent/parent/messages/$conversationId'
      path: '/parent/messages/$conversationId'
      fullPath: '/parent/messages/$conversationId'
      preLoaderRoute: typeof ParentParentMessagesConversationIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/enrollments/$enrollmentId': {
      id: '/_parent/parent/enrollments/$enrollmentId'
      path: '/parent/enrollments/$enrollmentId'
      fullPath: '/parent/enrollments/$enrollmentId'
      preLoaderRoute: typeof ParentParentEnrollmentsEnrollmentIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/documents/$documentId': {
      id: '/_parent/parent/documents/$documentId'
      path: '/parent/documents/$documentId'
      fullPath: '/parent/documents/$documentId'
      preLoaderRoute: typeof ParentParentDocumentsDocumentIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/children/new': {
      id: '/_parent/parent/children/new'
      path: '/parent/children/new'
      fullPath: '/parent/children/new'
      preLoaderRoute: typeof ParentParentChildrenNewRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/children/$childId': {
      id: '/_parent/parent/children/$childId'
      path: '/parent/children/$childId'
      fullPath: '/parent/children/$childId'
      preLoaderRoute: typeof ParentParentChildrenChildIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/billing/payments': {
      id: '/_parent/parent/billing/payments'
      path: '/parent/billing/payments'
      fullPath: '/parent/billing/payments'
      preLoaderRoute: typeof ParentParentBillingPaymentsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_parent/parent/billing/payment-methods': {
      id: '/_parent/parent/billing/payment-methods'
      path: '/parent/billing/payment-methods'
      fullPath: '/parent/billing/payment-methods'
      preLoaderRoute: typeof ParentParentBillingPaymentMethodsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_facility/facility/messages/$conversationId': {
      id: '/_facility/facility/messages/$conversationId'
      path: '/facility/messages/$conversationId'
      fullPath: '/facility/messages/$conversationId'
      preLoaderRoute: typeof FacilityFacilityMessagesConversationIdRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/staff': {
      id: '/_facility/facility/$facilityId/staff'
      path: '/facility/$facilityId/staff'
      fullPath: '/facility/$facilityId/staff'
      preLoaderRoute: typeof FacilityFacilityFacilityIdStaffRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/services': {
      id: '/_facility/facility/$facilityId/services'
      path: '/facility/$facilityId/services'
      fullPath: '/facility/$facilityId/services'
      preLoaderRoute: typeof FacilityFacilityFacilityIdServicesRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/roster': {
      id: '/_facility/facility/$facilityId/roster'
      path: '/facility/$facilityId/roster'
      fullPath: '/facility/$facilityId/roster'
      preLoaderRoute: typeof FacilityFacilityFacilityIdRosterRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/reviews': {
      id: '/_facility/facility/$facilityId/reviews'
      path: '/facility/$facilityId/reviews'
      fullPath: '/facility/$facilityId/reviews'
      preLoaderRoute: typeof FacilityFacilityFacilityIdReviewsRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/reports': {
      id: '/_facility/facility/$facilityId/reports'
      path: '/facility/$facilityId/reports'
      fullPath: '/facility/$facilityId/reports'
      preLoaderRoute: typeof FacilityFacilityFacilityIdReportsRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/photos': {
      id: '/_facility/facility/$facilityId/photos'
      path: '/facility/$facilityId/photos'
      fullPath: '/facility/$facilityId/photos'
      preLoaderRoute: typeof FacilityFacilityFacilityIdPhotosRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/invites': {
      id: '/_facility/facility/$facilityId/invites'
      path: '/facility/$facilityId/invites'
      fullPath: '/facility/$facilityId/invites'
      preLoaderRoute: typeof FacilityFacilityFacilityIdInvitesRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/hours': {
      id: '/_facility/facility/$facilityId/hours'
      path: '/facility/$facilityId/hours'
      fullPath: '/facility/$facilityId/hours'
      preLoaderRoute: typeof FacilityFacilityFacilityIdHoursRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/enrollments': {
      id: '/_facility/facility/$facilityId/enrollments'
      path: '/facility/$facilityId/enrollments'
      fullPath: '/facility/$facilityId/enrollments'
      preLoaderRoute: typeof FacilityFacilityFacilityIdEnrollmentsRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/edit': {
      id: '/_facility/facility/$facilityId/edit'
      path: '/facility/$facilityId/edit'
      fullPath: '/facility/$facilityId/edit'
      preLoaderRoute: typeof FacilityFacilityFacilityIdEditRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/daily-reports': {
      id: '/_facility/facility/$facilityId/daily-reports'
      path: '/facility/$facilityId/daily-reports'
      fullPath: '/facility/$facilityId/daily-reports'
      preLoaderRoute: typeof FacilityFacilityFacilityIdDailyReportsRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/attendance': {
      id: '/_facility/facility/$facilityId/attendance'
      path: '/facility/$facilityId/attendance'
      fullPath: '/facility/$facilityId/attendance'
      preLoaderRoute: typeof FacilityFacilityFacilityIdAttendanceRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/activities': {
      id: '/_facility/facility/$facilityId/activities'
      path: '/facility/$facilityId/activities'
      fullPath: '/facility/$facilityId/activities'
      preLoaderRoute: typeof FacilityFacilityFacilityIdActivitiesRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/documents/': {
      id: '/_facility/facility/$facilityId/documents/'
      path: '/facility/$facilityId/documents'
      fullPath: '/facility/$facilityId/documents/'
      preLoaderRoute: typeof FacilityFacilityFacilityIdDocumentsIndexRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/billing/': {
      id: '/_facility/facility/$facilityId/billing/'
      path: '/facility/$facilityId/billing'
      fullPath: '/facility/$facilityId/billing/'
      preLoaderRoute: typeof FacilityFacilityFacilityIdBillingIndexRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_parent/parent/children/$childId/photos': {
      id: '/_parent/parent/children/$childId/photos'
      path: '/photos'
      fullPath: '/parent/children/$childId/photos'
      preLoaderRoute: typeof ParentParentChildrenChildIdPhotosRouteImport
      parentRoute: typeof ParentParentChildrenChildIdRoute
    }
    '/_parent/parent/children/$childId/edit': {
      id: '/_parent/parent/children/$childId/edit'
      path: '/edit'
      fullPath: '/parent/children/$childId/edit'
      preLoaderRoute: typeof ParentParentChildrenChildIdEditRouteImport
      parentRoute: typeof ParentParentChildrenChildIdRoute
    }
    '/_parent/parent/children/$childId/activities': {
      id: '/_parent/parent/children/$childId/activities'
      path: '/activities'
      fullPath: '/parent/children/$childId/activities'
      preLoaderRoute: typeof ParentParentChildrenChildIdActivitiesRouteImport
      parentRoute: typeof ParentParentChildrenChildIdRoute
    }
    '/_parent/parent/billing/invoices/$invoiceId': {
      id: '/_parent/parent/billing/invoices/$invoiceId'
      path: '/parent/billing/invoices/$invoiceId'
      fullPath: '/parent/billing/invoices/$invoiceId'
      preLoaderRoute: typeof ParentParentBillingInvoicesInvoiceIdRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_facility/facility/$facilityId/invites/forms': {
      id: '/_facility/facility/$facilityId/invites/forms'
      path: '/forms'
      fullPath: '/facility/$facilityId/invites/forms'
      preLoaderRoute: typeof FacilityFacilityFacilityIdInvitesFormsRouteImport
      parentRoute: typeof FacilityFacilityFacilityIdInvitesRoute
    }
    '/_facility/facility/$facilityId/documents/templates': {
      id: '/_facility/facility/$facilityId/documents/templates'
      path: '/facility/$facilityId/documents/templates'
      fullPath: '/facility/$facilityId/documents/templates'
      preLoaderRoute: typeof FacilityFacilityFacilityIdDocumentsTemplatesRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/documents/send': {
      id: '/_facility/facility/$facilityId/documents/send'
      path: '/facility/$facilityId/documents/send'
      fullPath: '/facility/$facilityId/documents/send'
      preLoaderRoute: typeof FacilityFacilityFacilityIdDocumentsSendRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/documents/compliance': {
      id: '/_facility/facility/$facilityId/documents/compliance'
      path: '/facility/$facilityId/documents/compliance'
      fullPath: '/facility/$facilityId/documents/compliance'
      preLoaderRoute: typeof FacilityFacilityFacilityIdDocumentsComplianceRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/billing/invoices/': {
      id: '/_facility/facility/$facilityId/billing/invoices/'
      path: '/facility/$facilityId/billing/invoices'
      fullPath: '/facility/$facilityId/billing/invoices/'
      preLoaderRoute: typeof FacilityFacilityFacilityIdBillingInvoicesIndexRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_parent/parent/children/$childId/daily-report/$date': {
      id: '/_parent/parent/children/$childId/daily-report/$date'
      path: '/daily-report/$date'
      fullPath: '/parent/children/$childId/daily-report/$date'
      preLoaderRoute: typeof ParentParentChildrenChildIdDailyReportDateRouteImport
      parentRoute: typeof ParentParentChildrenChildIdRoute
    }
    '/_facility/facility/$facilityId/billing/invoices/new': {
      id: '/_facility/facility/$facilityId/billing/invoices/new'
      path: '/facility/$facilityId/billing/invoices/new'
      fullPath: '/facility/$facilityId/billing/invoices/new'
      preLoaderRoute: typeof FacilityFacilityFacilityIdBillingInvoicesNewRouteImport
      parentRoute: typeof FacilityRoute
    }
    '/_facility/facility/$facilityId/billing/invoices/$invoiceId': {
      id: '/_facility/facility/$facilityId/billing/invoices/$invoiceId'
      path: '/facility/$facilityId/billing/invoices/$invoiceId'
      fullPath: '/facility/$facilityId/billing/invoices/$invoiceId'
      preLoaderRoute: typeof FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRouteImport
      parentRoute: typeof FacilityRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface FacilityFacilityFacilityIdInvitesRouteChildren {
  FacilityFacilityFacilityIdInvitesFormsRoute: typeof FacilityFacilityFacilityIdInvitesFormsRoute
}

const FacilityFacilityFacilityIdInvitesRouteChildren: FacilityFacilityFacilityIdInvitesRouteChildren =
  {
    FacilityFacilityFacilityIdInvitesFormsRoute:
      FacilityFacilityFacilityIdInvitesFormsRoute,
  }

const FacilityFacilityFacilityIdInvitesRouteWithChildren =
  FacilityFacilityFacilityIdInvitesRoute._addFileChildren(
    FacilityFacilityFacilityIdInvitesRouteChildren,
  )

interface FacilityRouteChildren {
  FacilityFacilityNewRoute: typeof FacilityFacilityNewRoute
  FacilityFacilityNotificationsRoute: typeof FacilityFacilityNotificationsRoute
  FacilityFacilitySettingsRoute: typeof FacilityFacilitySettingsRoute
  FacilityFacilityIndexRoute: typeof FacilityFacilityIndexRoute
  FacilityFacilityFacilityIdActivitiesRoute: typeof FacilityFacilityFacilityIdActivitiesRoute
  FacilityFacilityFacilityIdAttendanceRoute: typeof FacilityFacilityFacilityIdAttendanceRoute
  FacilityFacilityFacilityIdDailyReportsRoute: typeof FacilityFacilityFacilityIdDailyReportsRoute
  FacilityFacilityFacilityIdEditRoute: typeof FacilityFacilityFacilityIdEditRoute
  FacilityFacilityFacilityIdEnrollmentsRoute: typeof FacilityFacilityFacilityIdEnrollmentsRoute
  FacilityFacilityFacilityIdHoursRoute: typeof FacilityFacilityFacilityIdHoursRoute
  FacilityFacilityFacilityIdInvitesRoute: typeof FacilityFacilityFacilityIdInvitesRouteWithChildren
  FacilityFacilityFacilityIdPhotosRoute: typeof FacilityFacilityFacilityIdPhotosRoute
  FacilityFacilityFacilityIdReportsRoute: typeof FacilityFacilityFacilityIdReportsRoute
  FacilityFacilityFacilityIdReviewsRoute: typeof FacilityFacilityFacilityIdReviewsRoute
  FacilityFacilityFacilityIdRosterRoute: typeof FacilityFacilityFacilityIdRosterRoute
  FacilityFacilityFacilityIdServicesRoute: typeof FacilityFacilityFacilityIdServicesRoute
  FacilityFacilityFacilityIdStaffRoute: typeof FacilityFacilityFacilityIdStaffRoute
  FacilityFacilityMessagesConversationIdRoute: typeof FacilityFacilityMessagesConversationIdRoute
  FacilityFacilityFacilityIdIndexRoute: typeof FacilityFacilityFacilityIdIndexRoute
  FacilityFacilityMessagesIndexRoute: typeof FacilityFacilityMessagesIndexRoute
  FacilityFacilityFacilityIdDocumentsComplianceRoute: typeof FacilityFacilityFacilityIdDocumentsComplianceRoute
  FacilityFacilityFacilityIdDocumentsSendRoute: typeof FacilityFacilityFacilityIdDocumentsSendRoute
  FacilityFacilityFacilityIdDocumentsTemplatesRoute: typeof FacilityFacilityFacilityIdDocumentsTemplatesRoute
  FacilityFacilityFacilityIdBillingIndexRoute: typeof FacilityFacilityFacilityIdBillingIndexRoute
  FacilityFacilityFacilityIdDocumentsIndexRoute: typeof FacilityFacilityFacilityIdDocumentsIndexRoute
  FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRoute: typeof FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRoute
  FacilityFacilityFacilityIdBillingInvoicesNewRoute: typeof FacilityFacilityFacilityIdBillingInvoicesNewRoute
  FacilityFacilityFacilityIdBillingInvoicesIndexRoute: typeof FacilityFacilityFacilityIdBillingInvoicesIndexRoute
}

const FacilityRouteChildren: FacilityRouteChildren = {
  FacilityFacilityNewRoute: FacilityFacilityNewRoute,
  FacilityFacilityNotificationsRoute: FacilityFacilityNotificationsRoute,
  FacilityFacilitySettingsRoute: FacilityFacilitySettingsRoute,
  FacilityFacilityIndexRoute: FacilityFacilityIndexRoute,
  FacilityFacilityFacilityIdActivitiesRoute:
    FacilityFacilityFacilityIdActivitiesRoute,
  FacilityFacilityFacilityIdAttendanceRoute:
    FacilityFacilityFacilityIdAttendanceRoute,
  FacilityFacilityFacilityIdDailyReportsRoute:
    FacilityFacilityFacilityIdDailyReportsRoute,
  FacilityFacilityFacilityIdEditRoute: FacilityFacilityFacilityIdEditRoute,
  FacilityFacilityFacilityIdEnrollmentsRoute:
    FacilityFacilityFacilityIdEnrollmentsRoute,
  FacilityFacilityFacilityIdHoursRoute: FacilityFacilityFacilityIdHoursRoute,
  FacilityFacilityFacilityIdInvitesRoute:
    FacilityFacilityFacilityIdInvitesRouteWithChildren,
  FacilityFacilityFacilityIdPhotosRoute: FacilityFacilityFacilityIdPhotosRoute,
  FacilityFacilityFacilityIdReportsRoute:
    FacilityFacilityFacilityIdReportsRoute,
  FacilityFacilityFacilityIdReviewsRoute:
    FacilityFacilityFacilityIdReviewsRoute,
  FacilityFacilityFacilityIdRosterRoute: FacilityFacilityFacilityIdRosterRoute,
  FacilityFacilityFacilityIdServicesRoute:
    FacilityFacilityFacilityIdServicesRoute,
  FacilityFacilityFacilityIdStaffRoute: FacilityFacilityFacilityIdStaffRoute,
  FacilityFacilityMessagesConversationIdRoute:
    FacilityFacilityMessagesConversationIdRoute,
  FacilityFacilityFacilityIdIndexRoute: FacilityFacilityFacilityIdIndexRoute,
  FacilityFacilityMessagesIndexRoute: FacilityFacilityMessagesIndexRoute,
  FacilityFacilityFacilityIdDocumentsComplianceRoute:
    FacilityFacilityFacilityIdDocumentsComplianceRoute,
  FacilityFacilityFacilityIdDocumentsSendRoute:
    FacilityFacilityFacilityIdDocumentsSendRoute,
  FacilityFacilityFacilityIdDocumentsTemplatesRoute:
    FacilityFacilityFacilityIdDocumentsTemplatesRoute,
  FacilityFacilityFacilityIdBillingIndexRoute:
    FacilityFacilityFacilityIdBillingIndexRoute,
  FacilityFacilityFacilityIdDocumentsIndexRoute:
    FacilityFacilityFacilityIdDocumentsIndexRoute,
  FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRoute:
    FacilityFacilityFacilityIdBillingInvoicesInvoiceIdRoute,
  FacilityFacilityFacilityIdBillingInvoicesNewRoute:
    FacilityFacilityFacilityIdBillingInvoicesNewRoute,
  FacilityFacilityFacilityIdBillingInvoicesIndexRoute:
    FacilityFacilityFacilityIdBillingInvoicesIndexRoute,
}

const FacilityRouteWithChildren = FacilityRoute._addFileChildren(
  FacilityRouteChildren,
)

interface ParentParentChildrenChildIdRouteChildren {
  ParentParentChildrenChildIdActivitiesRoute: typeof ParentParentChildrenChildIdActivitiesRoute
  ParentParentChildrenChildIdEditRoute: typeof ParentParentChildrenChildIdEditRoute
  ParentParentChildrenChildIdPhotosRoute: typeof ParentParentChildrenChildIdPhotosRoute
  ParentParentChildrenChildIdDailyReportDateRoute: typeof ParentParentChildrenChildIdDailyReportDateRoute
}

const ParentParentChildrenChildIdRouteChildren: ParentParentChildrenChildIdRouteChildren =
  {
    ParentParentChildrenChildIdActivitiesRoute:
      ParentParentChildrenChildIdActivitiesRoute,
    ParentParentChildrenChildIdEditRoute: ParentParentChildrenChildIdEditRoute,
    ParentParentChildrenChildIdPhotosRoute:
      ParentParentChildrenChildIdPhotosRoute,
    ParentParentChildrenChildIdDailyReportDateRoute:
      ParentParentChildrenChildIdDailyReportDateRoute,
  }

const ParentParentChildrenChildIdRouteWithChildren =
  ParentParentChildrenChildIdRoute._addFileChildren(
    ParentParentChildrenChildIdRouteChildren,
  )

interface ParentRouteChildren {
  ParentParentNotificationsRoute: typeof ParentParentNotificationsRoute
  ParentParentReviewsRoute: typeof ParentParentReviewsRoute
  ParentParentSettingsRoute: typeof ParentParentSettingsRoute
  ParentParentIndexRoute: typeof ParentParentIndexRoute
  ParentParentBillingPaymentMethodsRoute: typeof ParentParentBillingPaymentMethodsRoute
  ParentParentBillingPaymentsRoute: typeof ParentParentBillingPaymentsRoute
  ParentParentChildrenChildIdRoute: typeof ParentParentChildrenChildIdRouteWithChildren
  ParentParentChildrenNewRoute: typeof ParentParentChildrenNewRoute
  ParentParentDocumentsDocumentIdRoute: typeof ParentParentDocumentsDocumentIdRoute
  ParentParentEnrollmentsEnrollmentIdRoute: typeof ParentParentEnrollmentsEnrollmentIdRoute
  ParentParentMessagesConversationIdRoute: typeof ParentParentMessagesConversationIdRoute
  ParentParentBillingIndexRoute: typeof ParentParentBillingIndexRoute
  ParentParentChildrenIndexRoute: typeof ParentParentChildrenIndexRoute
  ParentParentDocumentsIndexRoute: typeof ParentParentDocumentsIndexRoute
  ParentParentMessagesIndexRoute: typeof ParentParentMessagesIndexRoute
  ParentParentBillingInvoicesInvoiceIdRoute: typeof ParentParentBillingInvoicesInvoiceIdRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentParentNotificationsRoute: ParentParentNotificationsRoute,
  ParentParentReviewsRoute: ParentParentReviewsRoute,
  ParentParentSettingsRoute: ParentParentSettingsRoute,
  ParentParentIndexRoute: ParentParentIndexRoute,
  ParentParentBillingPaymentMethodsRoute:
    ParentParentBillingPaymentMethodsRoute,
  ParentParentBillingPaymentsRoute: ParentParentBillingPaymentsRoute,
  ParentParentChildrenChildIdRoute:
    ParentParentChildrenChildIdRouteWithChildren,
  ParentParentChildrenNewRoute: ParentParentChildrenNewRoute,
  ParentParentDocumentsDocumentIdRoute: ParentParentDocumentsDocumentIdRoute,
  ParentParentEnrollmentsEnrollmentIdRoute:
    ParentParentEnrollmentsEnrollmentIdRoute,
  ParentParentMessagesConversationIdRoute:
    ParentParentMessagesConversationIdRoute,
  ParentParentBillingIndexRoute: ParentParentBillingIndexRoute,
  ParentParentChildrenIndexRoute: ParentParentChildrenIndexRoute,
  ParentParentDocumentsIndexRoute: ParentParentDocumentsIndexRoute,
  ParentParentMessagesIndexRoute: ParentParentMessagesIndexRoute,
  ParentParentBillingInvoicesInvoiceIdRoute:
    ParentParentBillingInvoicesInvoiceIdRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StaffRouteChildren {
  StaffStaffNotificationsRoute: typeof StaffStaffNotificationsRoute
  StaffStaffSettingsRoute: typeof StaffStaffSettingsRoute
  StaffStaffIndexRoute: typeof StaffStaffIndexRoute
  StaffStaffMessagesConversationIdRoute: typeof StaffStaffMessagesConversationIdRoute
  StaffStaffMessagesIndexRoute: typeof StaffStaffMessagesIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffStaffNotificationsRoute: StaffStaffNotificationsRoute,
  StaffStaffSettingsRoute: StaffStaffSettingsRoute,
  StaffStaffIndexRoute: StaffStaffIndexRoute,
  StaffStaffMessagesConversationIdRoute: StaffStaffMessagesConversationIdRoute,
  StaffStaffMessagesIndexRoute: StaffStaffMessagesIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  FacilityRoute: FacilityRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  InviteCodeRoute: InviteCodeRoute,
  FacilitiesIndexRoute: FacilitiesIndexRoute,
  FacilitiesFacilityIdEnrollRoute: FacilitiesFacilityIdEnrollRoute,
  FacilitiesFacilityIdReviewRoute: FacilitiesFacilityIdReviewRoute,
  FacilitiesFacilityIdIndexRoute: FacilitiesFacilityIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
