/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParentRouteImport } from './routes/_parent'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentParentRouteImport } from './routes/_parent/parent'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminFacilitySetupRouteImport } from './routes/_admin/facility/setup'
import { Route as AdminFacilityNewRouteImport } from './routes/_admin/facility/new'
import { Route as AdminFacilityFacilityIdRouteImport } from './routes/_admin/facility/$facilityId'
import { Route as AdminFacilityFacilityIdIndexRouteImport } from './routes/_admin/facility/$facilityId/index'
import { Route as AdminFacilityFacilityIdGuardiansRouteImport } from './routes/_admin/facility/$facilityId/guardians'
import { Route as AdminFacilityFacilityIdChildrenRouteImport } from './routes/_admin/facility/$facilityId/children'
import { Route as AdminFacilityFacilityIdAttendanceRouteImport } from './routes/_admin/facility/$facilityId/attendance'
import { Route as AdminFacilityFacilityIdChildrenChildIdRouteImport } from './routes/_admin/facility/$facilityId/children_.$childId'

const ParentRoute = ParentRouteImport.update({
  id: '/_parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentParentRoute = ParentParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => ParentRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFacilitySetupRoute = AdminFacilitySetupRouteImport.update({
  id: '/facility/setup',
  path: '/facility/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilityNewRoute = AdminFacilityNewRouteImport.update({
  id: '/facility/new',
  path: '/facility/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilityFacilityIdRoute = AdminFacilityFacilityIdRouteImport.update({
  id: '/facility/$facilityId',
  path: '/facility/$facilityId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilityFacilityIdIndexRoute =
  AdminFacilityFacilityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminFacilityFacilityIdRoute,
  } as any)
const AdminFacilityFacilityIdGuardiansRoute =
  AdminFacilityFacilityIdGuardiansRouteImport.update({
    id: '/guardians',
    path: '/guardians',
    getParentRoute: () => AdminFacilityFacilityIdRoute,
  } as any)
const AdminFacilityFacilityIdChildrenRoute =
  AdminFacilityFacilityIdChildrenRouteImport.update({
    id: '/children',
    path: '/children',
    getParentRoute: () => AdminFacilityFacilityIdRoute,
  } as any)
const AdminFacilityFacilityIdAttendanceRoute =
  AdminFacilityFacilityIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AdminFacilityFacilityIdRoute,
  } as any)
const AdminFacilityFacilityIdChildrenChildIdRoute =
  AdminFacilityFacilityIdChildrenChildIdRouteImport.update({
    id: '/children_/$childId',
    path: '/children/$childId',
    getParentRoute: () => AdminFacilityFacilityIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/parent': typeof ParentParentRoute
  '/facility/$facilityId': typeof AdminFacilityFacilityIdRouteWithChildren
  '/facility/new': typeof AdminFacilityNewRoute
  '/facility/setup': typeof AdminFacilitySetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/facility/$facilityId/attendance': typeof AdminFacilityFacilityIdAttendanceRoute
  '/facility/$facilityId/children': typeof AdminFacilityFacilityIdChildrenRoute
  '/facility/$facilityId/guardians': typeof AdminFacilityFacilityIdGuardiansRoute
  '/facility/$facilityId/': typeof AdminFacilityFacilityIdIndexRoute
  '/facility/$facilityId/children/$childId': typeof AdminFacilityFacilityIdChildrenChildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/parent': typeof ParentParentRoute
  '/facility/new': typeof AdminFacilityNewRoute
  '/facility/setup': typeof AdminFacilitySetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/facility/$facilityId/attendance': typeof AdminFacilityFacilityIdAttendanceRoute
  '/facility/$facilityId/children': typeof AdminFacilityFacilityIdChildrenRoute
  '/facility/$facilityId/guardians': typeof AdminFacilityFacilityIdGuardiansRoute
  '/facility/$facilityId': typeof AdminFacilityFacilityIdIndexRoute
  '/facility/$facilityId/children/$childId': typeof AdminFacilityFacilityIdChildrenChildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_parent': typeof ParentRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_parent/parent': typeof ParentParentRoute
  '/_admin/facility/$facilityId': typeof AdminFacilityFacilityIdRouteWithChildren
  '/_admin/facility/new': typeof AdminFacilityNewRoute
  '/_admin/facility/setup': typeof AdminFacilitySetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/facility/$facilityId/attendance': typeof AdminFacilityFacilityIdAttendanceRoute
  '/_admin/facility/$facilityId/children': typeof AdminFacilityFacilityIdChildrenRoute
  '/_admin/facility/$facilityId/guardians': typeof AdminFacilityFacilityIdGuardiansRoute
  '/_admin/facility/$facilityId/': typeof AdminFacilityFacilityIdIndexRoute
  '/_admin/facility/$facilityId/children_/$childId': typeof AdminFacilityFacilityIdChildrenChildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/parent'
    | '/facility/$facilityId'
    | '/facility/new'
    | '/facility/setup'
    | '/api/auth/$'
    | '/facility/$facilityId/attendance'
    | '/facility/$facilityId/children'
    | '/facility/$facilityId/guardians'
    | '/facility/$facilityId/'
    | '/facility/$facilityId/children/$childId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/parent'
    | '/facility/new'
    | '/facility/setup'
    | '/api/auth/$'
    | '/facility/$facilityId/attendance'
    | '/facility/$facilityId/children'
    | '/facility/$facilityId/guardians'
    | '/facility/$facilityId'
    | '/facility/$facilityId/children/$childId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_parent'
    | '/_admin/dashboard'
    | '/_auth/login'
    | '/_auth/register'
    | '/_parent/parent'
    | '/_admin/facility/$facilityId'
    | '/_admin/facility/new'
    | '/_admin/facility/setup'
    | '/api/auth/$'
    | '/_admin/facility/$facilityId/attendance'
    | '/_admin/facility/$facilityId/children'
    | '/_admin/facility/$facilityId/guardians'
    | '/_admin/facility/$facilityId/'
    | '/_admin/facility/$facilityId/children_/$childId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_parent': {
      id: '/_parent'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_parent/parent': {
      id: '/_parent/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentParentRouteImport
      parentRoute: typeof ParentRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/facility/setup': {
      id: '/_admin/facility/setup'
      path: '/facility/setup'
      fullPath: '/facility/setup'
      preLoaderRoute: typeof AdminFacilitySetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/facility/new': {
      id: '/_admin/facility/new'
      path: '/facility/new'
      fullPath: '/facility/new'
      preLoaderRoute: typeof AdminFacilityNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/facility/$facilityId': {
      id: '/_admin/facility/$facilityId'
      path: '/facility/$facilityId'
      fullPath: '/facility/$facilityId'
      preLoaderRoute: typeof AdminFacilityFacilityIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/facility/$facilityId/': {
      id: '/_admin/facility/$facilityId/'
      path: '/'
      fullPath: '/facility/$facilityId/'
      preLoaderRoute: typeof AdminFacilityFacilityIdIndexRouteImport
      parentRoute: typeof AdminFacilityFacilityIdRoute
    }
    '/_admin/facility/$facilityId/guardians': {
      id: '/_admin/facility/$facilityId/guardians'
      path: '/guardians'
      fullPath: '/facility/$facilityId/guardians'
      preLoaderRoute: typeof AdminFacilityFacilityIdGuardiansRouteImport
      parentRoute: typeof AdminFacilityFacilityIdRoute
    }
    '/_admin/facility/$facilityId/children': {
      id: '/_admin/facility/$facilityId/children'
      path: '/children'
      fullPath: '/facility/$facilityId/children'
      preLoaderRoute: typeof AdminFacilityFacilityIdChildrenRouteImport
      parentRoute: typeof AdminFacilityFacilityIdRoute
    }
    '/_admin/facility/$facilityId/attendance': {
      id: '/_admin/facility/$facilityId/attendance'
      path: '/attendance'
      fullPath: '/facility/$facilityId/attendance'
      preLoaderRoute: typeof AdminFacilityFacilityIdAttendanceRouteImport
      parentRoute: typeof AdminFacilityFacilityIdRoute
    }
    '/_admin/facility/$facilityId/children_/$childId': {
      id: '/_admin/facility/$facilityId/children_/$childId'
      path: '/children/$childId'
      fullPath: '/facility/$facilityId/children/$childId'
      preLoaderRoute: typeof AdminFacilityFacilityIdChildrenChildIdRouteImport
      parentRoute: typeof AdminFacilityFacilityIdRoute
    }
  }
}

interface AdminFacilityFacilityIdRouteChildren {
  AdminFacilityFacilityIdAttendanceRoute: typeof AdminFacilityFacilityIdAttendanceRoute
  AdminFacilityFacilityIdChildrenRoute: typeof AdminFacilityFacilityIdChildrenRoute
  AdminFacilityFacilityIdGuardiansRoute: typeof AdminFacilityFacilityIdGuardiansRoute
  AdminFacilityFacilityIdIndexRoute: typeof AdminFacilityFacilityIdIndexRoute
  AdminFacilityFacilityIdChildrenChildIdRoute: typeof AdminFacilityFacilityIdChildrenChildIdRoute
}

const AdminFacilityFacilityIdRouteChildren: AdminFacilityFacilityIdRouteChildren =
  {
    AdminFacilityFacilityIdAttendanceRoute:
      AdminFacilityFacilityIdAttendanceRoute,
    AdminFacilityFacilityIdChildrenRoute: AdminFacilityFacilityIdChildrenRoute,
    AdminFacilityFacilityIdGuardiansRoute:
      AdminFacilityFacilityIdGuardiansRoute,
    AdminFacilityFacilityIdIndexRoute: AdminFacilityFacilityIdIndexRoute,
    AdminFacilityFacilityIdChildrenChildIdRoute:
      AdminFacilityFacilityIdChildrenChildIdRoute,
  }

const AdminFacilityFacilityIdRouteWithChildren =
  AdminFacilityFacilityIdRoute._addFileChildren(
    AdminFacilityFacilityIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFacilityFacilityIdRoute: typeof AdminFacilityFacilityIdRouteWithChildren
  AdminFacilityNewRoute: typeof AdminFacilityNewRoute
  AdminFacilitySetupRoute: typeof AdminFacilitySetupRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFacilityFacilityIdRoute: AdminFacilityFacilityIdRouteWithChildren,
  AdminFacilityNewRoute: AdminFacilityNewRoute,
  AdminFacilitySetupRoute: AdminFacilitySetupRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ParentRouteChildren {
  ParentParentRoute: typeof ParentParentRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentParentRoute: ParentParentRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
